services:
  postgres:
    image: postgres:15-alpine
    container_name: tpn_ci_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-tpn}
      - POSTGRES_USER=${POSTGRES_USER:-tpn}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - tpn-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tpn} -d ${POSTGRES_DB:-tpn}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


networks:
  # Internal network - has internal connectivity only, cannot reach internet or be reached from it
  tpn-internal:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: ${TPN_INTERNAL_SUBNET:-172.20.0.0/16}
          gateway: ${TPN_INTERNAL_GATEWAY:-172.20.0.1}
